import paddle.v2 as paddle
import numpy as np



paddle.init(use_gpu=False)
x = paddle.layer.data(name='x', type=paddle.data_type.dense_vector(2))
y_predict = paddle.layer.fc(input=x, size=1, act=paddle.activation.Linear())

# loading the model which generated by training
with open('params_pass_20.tar', 'r') as f:
    parameters = paddle.parameters.Parameters.from_tar(f)

i = [[[1, 2]], [[3, 4]], [[5, 6]]]
probs =  paddle.infer(output_layer=y_predict, parameters=parameters, input=i)
print(probs)
